name: AutoPost

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 8:00 AM UTC on Monday, Wednesday, and Friday
    - cron: '0 8 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace
      uses: AutoModality/action-clean@v1
      with:
        clean: true

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Instagram poster script
      run: python app.py
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}