name: AutoPost

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 8:00 AM UTC on Monday, Wednesday, and Friday
    - cron: '0 8 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace
      uses: AutoModality/action-clean@v1
      with:
        clean: true

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dev Proxy
      run: bash -c "$(curl -sL https://aka.ms/devproxy/setup.sh)"

    - name: Run Dev Proxy
      run: ./devproxy/devproxy &

    - name: Install the Dev Proxy's certificate
      timeout-minutes: 1
      run: |
        echo "Export the Dev Proxy's Root Certificate"
        openssl pkcs12 -in ~/.config/dev-proxy/rootCert.pfx -clcerts -nokeys -out dev-proxy-ca.crt -passin pass:""

        echo "Installing the Dev Proxy's Root Certificate"
        sudo cp dev-proxy-ca.crt /usr/local/share/ca-certificates/

        echo "Updating the CA certificates"
        sudo update-ca-certificates
        echo "Certificate trusted."

        # Set the system proxy settings (optional)
        echo "http_proxy=http://127.0.0.1:8000" >> $GITHUB_ENV
        echo "https_proxy=http://127.0.0.1:8000" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Directory Check 2
      run: |
        pwd
        ls -a
    - name: Run Instagram poster script
      run: python app.py
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}